### ISSUE TITLE
Is there a reason for not having CFITSIO for Julia 1.0, 1.1 and 1.2?

### ISSUE THREAD

**Issue by emmt** [JuliaAstro/CFITSIO.jl#2]
When doing `pkg> add CFITSIO` in Julia 1.0 to 1.2 (inclusive), I get the following error:

    ERROR: failed to clone from CFITSIO,, error: GitError(Code:ERROR, Class:Net, unsupported URL protocol)

is it on purpose or is because no backward compatibility is possible?

**Comment by giordano** [comment]
This package won't work anyway in Julia v1.2-, but that error doesn't seem to be related a compatibility issue in the package manager.  This is what I get in Julia v1.0:
```
(v1.0) pkg> add CFITSIO
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package CFITSIO [3b1b4be9]:
 CFITSIO [3b1b4be9] log:
 ├─possible versions are: 1.0.0 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 1.0.0
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by giordano** [comment]
Regarding the reason, this package depends on the JLL package `CFITSIO_jll`.  JLL packages only work in Julia v1.3+.

**Comment by emmt** [comment]
OK I understand.  Anyway, everyone is encouraged to use the most recent stable version of Julia....
