### ISSUE TITLE
What if we just permuted the data

### ISSUE THREAD

**Issue by mileslucas** [JuliaAstro/CFITSIO.jl#7]
What if we just permuted data on read? I'd like to see the arguments against, but I would really prefer to see data in its row-major orientation by default.

In terms of implementation, I have no clue what the most efficient and transparent solution is besides calling `permutedims`. I'm interested how PyCall.jl facilitates this when it hands off arrays to numpy.

cc @giordano

**Comment by giordano** [comment]
If I remember correctly, also @helgee had a similar issue with other packages (ERFA?)

**Comment by helgee** [comment]
ERFA.jl and SPICE.jl both use `permutedims`.

**Comment by jishnub** [comment]
Perhaps a better idea would be to provide an option to the caller to permute the data on read. Permuting by default might not be ideal, since this changes the contiguity of data.
